name: new_csintranetapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^4.4.9
  google_fonts: ^2.1.0
  device_info_plus: ^3.1.1

  #UI
  animate_do: ^2.0.0
  package_info: ^2.0.2
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0

  #STATE MANAGEMENT
  provider: ^6.0.1

  #STORAGE & PERMISSION
  permission_handler: ^8.1.6
  flutter_downloader: ^1.7.0
  path_provider: ^2.0.5

  #CONNECTIVITY
#  http: ^0.13.3
  dio: ^4.0.1
  connectivity: ^3.0.6
  url_launcher: ^6.0.12
  store_redirect: ^2.0.0
  new_version: ^0.2.3

  # WEB TOOLS
  flutter_inappwebview: ^5.3.2
  firebase_dynamic_links: ^2.0.10
  syncfusion_flutter_pdfviewer: ^19.3.45-beta

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/

